language: node_js

node_js:
- '6'
- '4'

sudo: false

cache:
  directories:
  - $HOME/.yarn-cache
  - $HOME/.bats

before_install:
- git clone https://github.com/sstephenson/bats.git .bats
- yarn global add greenkeeper-lockfile@1

before_script:
- greenkeeper-lockfile-update
- npm run compile

script: npm test

after_script: greenkeeper-lockfile-upload

after_success: npm run codecov

deploy:
  provider: npm
  email: git@jwr.vc
  api_key:
    secure: K/+dVjtCqesr5E5EMZo/qBdKlWwPpZ60yp1GtKoAhSZUtL4VY4A8LOJmcSeIeYvsPkK8PRSCyb2FTDfSTYEO4dWVfNPoLxWp7U48iIiHSfLdNixfTiBHyjdKdP/6oCz3TNfb9upPUb1lcb5h+rM2KJgCLT6s30Vbajka6STeDCs=
  on:
    tags: true
    repo: jamesramsay/hercule
