image: node:10

test:
  before_script:
    - npm install
  script:
    - npm test

code_intelligence:
  before_script:
    - npm install
  script:
    - npm run lsif
  artifacts:
    reports:
      lsif: dump.lsif
